Fix a function has no attribute "read" error.
On at least Python2.7, I can't install this as a dependency in another setup.py
because it fails with:
`AttributeError: 'function' object has no attribute 'read'`

I'm not sure if this breaks other versions or if it's just something in my setup, but it scratches my itch.